name: CI

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build & Deploy
    runs-on: [self-hosted]

    steps:
      - name: Checkout
        run: |
          rm -rf ~/UML_Mentor/
          mkdir ~/UML_Mentor
          cd ~/UML_Mentor
          git switch main
          git pull
          npm install

      - name: Build Client
        run: |
          cd ~/UML_Mentor/client
          npm install && npm run build

      - name: Start Server
        run: |
          cd ~/UML_Mentor
          cp ~/env_file .env
          pm2 restart "UML Mentor"
