name: CI

on:
  push:
    branches:
      - main
      # Delete this line
      - 39-setup-github-actions-for-repo

jobs:
  build-deploy:
    name: Build & Deploy
    runs-on: [self-hosted]

    steps:
      - name: Checkout
        # TODO: git checkout to main
        run: |
          cd ~/UML_Mentor
          git switch 39-setup-github-actions-for-repo
          git pull

      - name: Build Client
        run: |
          cd ~/UML_Mentor/client
          npm install && npm run build

      - name: Start Server
        run: |
          cd ~/UML_Mentor
          cp ~/.env .
          
          

#  start-server:
#    name: Start Express Server
#    runs-on: [self-hosted]
#
#    steps:
#      - name: Checkout Repository
#        uses: actions/checkout@v2
#
#      - name: Install Dependencies and Start Server
#        run: |
#          npm install
#          npm start
