name: CI

on:
  push:
    branches:
      - main
      # Delete this line
      - 39-setup-github-actions-for-repo

jobs:
  build-deploy:
    name: Build & Deploy
    runs-on: [self-hosted]

    steps:
      - name: Checkout
        # TODO: add npm run lint
        run: |
          cd ~/UML_Mentor
          git pull

      - name: Build Client
        run: |
          pwd
          cd ~/UML_Mentor

      - name: Start Server
        run: |
          pwd
          

#  start-server:
#    name: Start Express Server
#    runs-on: [self-hosted]
#
#    steps:
#      - name: Checkout Repository
#        uses: actions/checkout@v2
#
#      - name: Install Dependencies and Start Server
#        run: |
#          npm install
#          npm start
